### PR TITLE
Grouping and sorting datasets

### LINKED ISSUE #385: Allow for grouping datasets
It should be possible to group datasets in the UI for server configurations with many datasets. 

image

### PR DESCRIPTION
**Pull request by forman**
Closes #385

Requires https://github.com/xcube-dev/xcube/pull/1039

image

### CODE REVIEW

**Review by konstntokas — COMMENTED** [review]
I barely know any react. I could figure out, what the code does but I do not feel sufficiently knowledgeable to give a review on this. 

I think it would be nice, if the group name is deleted from the dataset name, which will improve visibility especially for longer group names. @gunbra32 has shown an example last week with very long dataset names where the biggest part of the name was the actual group name.

**Comment by forman** [comment]
> if the group name is deleted from the dataset name

Both title and group name are set by the user. I don't see any need to manipulate what a user configured.

**Comment by forman** [comment]
> I barely know any react. 

Code changes are trivial. I only want you to review the UI, i.e., verify that it works. That's all.

**Review by konstntokas — APPROVED** [review]
Works as expected 

Screenshot from 2024-07-15 15-33-39

**Pull request merged**
