### PR TITLE
User-defined variables

### LINKED ISSUE #371: User-defined variables
In order to deeper analyse variables of a cube dataset, it is often desired to compute variables from arbitrary band-math expressions. 
Users should be able to define new variables and add them to the respective datasets. For example, to analyse the difference of two variables, users should be able to define a new variable `chl12_dev = (chl1 - chl2) ** 2`. 

The user-defined variables should be persisted in the browser's local storage as we currently do not support server-side persistence of user data. To let the server know about user-defined variables, xcube API endpoints that currently receive a variable name in their URL path should then accept an URL-encoded variable assignment expression of the form `<var_name>=<var_expr>`, where `<var_name>` is the name user defined variable and `<var_expr>` is an arbitrary band-math expression.

### PR DESCRIPTION
**Pull request by forman**
Added new dialog to define user variables for a selected dataset. Whenever user variables change, they are stored in the browsers local storage given the selected dataset's identifier and the list of associated user variables.

image

A user variable can be selected as any other variable. In the list of dataset variables they are marked with a special icon.

image

User variables should work with all viewer functionality. With a user variable selected, check

- info panel
- time-series panel
- statistics panel
- volume panel

Closes #371 

Requires backend implementation https://github.com/xcube-dev/xcube/pull/1021

### CODE REVIEW

**Comment by konstntokas** [comment]
What does `min` and `max` do? Is it the minimal and maximal values along the time axis? I have tried it out in the Viewer, but no data is shown.

**Comment by ruchimotwaniBC** [comment]
> What does `min` and `max` do? Is it the minimal and maximal values along the time axis? I have tried it out in the Viewer, but no data is shown.

True, I also the same question :) 
image

**Comment by ruchimotwaniBC** [comment]
image

Since this variables are user defined and will not be found in the data, should we disable `Volume` tab for user defined variables or is it that we are explicitly showing this message to user?

**Review by ruchimotwaniBC — CHANGES_REQUESTED** [review]
Two comments, else its working fine.

**Comment by forman** [comment]
> What does `min` and `max` do? Is it the minimal and maximal values along the time axis? I have tried it out in the Viewer, but no data is shown.

I have excluded `min` / `max` from the backend. Will do so for UI.

**Comment by forman** [comment]
> Since this variables are user defined and will not be found in the data, should we disable `Volume` tab for user defined variables or is it that we are explicitly showing this message to user?

That should be working now.

**Review by ruchimotwaniBC — APPROVED** [review]

**Pull request merged**
