### PR TITLE
Made right Side panel's tab bar sticky

### PR DESCRIPTION
**Pull request by ruchimotwaniBC**

### CODE REVIEW

**Review by forman — CHANGES_REQUESTED** [review]
Please revert changes in CHANGES.md

**Comment by forman** [comment]
Please update `CHANGES.md` with what has been done rather than just reformatting it.

**Comment by ruchimotwaniBC** [comment]
> Please update `CHANGES.md` with what has been done rather than just reformatting it.

I have added what have been done but the formatting happened because of prettier. Earlier it never happened.

**Review by forman — APPROVED** [review]
Works nice!

**Pull request merged**
